// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgjX0BErf_EgWbAfJlox0qDiml6ybFTWA',
    appId: '1:68770966285:web:05fbdfdf058be659c1de44',
    messagingSenderId: '68770966285',
    projectId: 'azurneobank',
    authDomain: 'azurneobank.firebaseapp.com',
    storageBucket: 'azurneobank.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3pCnfucXfv8JGgt6919cg3BOfMl7zkRs',
    appId: '1:68770966285:android:7d12d1f7f99119b8c1de44',
    messagingSenderId: '68770966285',
    projectId: 'azurneobank',
    storageBucket: 'azurneobank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD8pYJeUQyuobm0_Ix_SZ-8NAjTbK4jOo',
    appId: '1:68770966285:ios:8f9061562aa324c1c1de44',
    messagingSenderId: '68770966285',
    projectId: 'azurneobank',
    storageBucket: 'azurneobank.appspot.com',
    iosClientId: '68770966285-5fgsu8ke3efs2p2r88dci5av8kgm5q82.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD8pYJeUQyuobm0_Ix_SZ-8NAjTbK4jOo',
    appId: '1:68770966285:ios:8f9061562aa324c1c1de44',
    messagingSenderId: '68770966285',
    projectId: 'azurneobank',
    storageBucket: 'azurneobank.appspot.com',
    iosClientId: '68770966285-5fgsu8ke3efs2p2r88dci5av8kgm5q82.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocTraining',
  );
}
